# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localities',
            old_name='uploaded_at',
            new_name='uploaded_At',
        ),
    ]
