# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0002_auto_20180513_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localities',
            name='playGrounds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_cleanliness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_locality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_parks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localities',
            name='rate_security',
            field=models.IntegerField(),
        ),
    ]
