# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFYP', '0006_auto_20180513_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localities',
            name='location',
            field=models.CharField(choices=[('mustafa town', 'mustafa town'), ('iqbal town', 'iqbal town'), ('johar town', 'johar town'), ('defence', 'defence'), ('Awan town', 'Awan town'), ('Wapda town', 'Wapda town'), ('Eden', 'Eden'), ('Lake city', 'Lake city')], default='johar town', max_length=136),
        ),
        migrations.AlterField(
            model_name='products',
            name='location',
            field=models.CharField(choices=[('mustafa town', 'mustafa town'), ('iqbal town', 'iqbal town'), ('johar town', 'johar town'), ('defence', 'defence'), ('Awan town', 'Awan town'), ('Wapda town', 'Wapda town'), ('Eden', 'Eden'), ('Lake city', 'Lake city')], default='mustafa_town', max_length=30),
        ),
    ]
